### ISSUE TITLE
password problem when used from Xamarin studio

### ISSUE THREAD

**Issue by GrahamBriggs** [logicethos/SSHDebugger#3]
On a Mac, Using Xamarin studio, I installed the plugin from add in manager.

Added file and set user name and host address for raspberry pi.

When I run using ssh debug, terminal window appears and prompts me for password for the user.  I have tried several times, but it always refuses the password

Running script: remote-host.ssh.txt
Enter Host Password: **********
sftp connecting to pi@192.168.1.40:22...Error: Permission denied (password).

I watched the video, there is no login prompt in the example there.

I have checked connection using mac terminal, and I am sure the password and ip address for the pi is correct in the remote-host.ssh.txt file.

Any help on this issue is greatly appreciated. If I can get this to work, it is a game changer for me

**Comment by rocuh** [comment]
I had the same issue, for anyone else you can do pi:raspberry@192.168.1.40:22 where raspberry in this case is the password

**Comment by Int32Overflow** [comment]
Issue fixed
