### ISSUE TITLE
Problem & Solution:  Could not get valid MDB to generate

### ISSUE THREAD

**Issue by Opzet** [logicethos/SSHDebugger#6]
Got file not found with mdb

> The problem is that the pdb2mdb.exe is executed using the .NET framework. But the .exe was actually build with the Mono framework. So this gives us the problem. The solution is to call the pdb2mdb.exe with the Mono runtime. Josh proposes to either use the direct call:

Xamarin Studio->Project Options->Build->CustomCommands

Added  "After build" "Run on external console"

"C:\Program Files (x86)\Mono\bin\mono.exe" "C:\Program Files (x86)\Mono\lib\mono\4.5\pdb2mdb.exe" ${TargetFile}

**Comment by Int32Overflow** [comment]
New version can work with pdb files => Issue solved
